services:
  hermes-rag:
    build: ./hermes-rag
    container_name: hermes-rag
    volumes:
      - /media/sacha/de202ea4-0195-4fcc-85f1-3ca679ce2cdf1/models:/app/models:rw
    networks:
      - ai-net
    ports:
      - "5000:5000"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - /media/sacha/de202ea4-0195-4fcc-85f1-3ca679ce2cdf1/models:/root/.ollama/models:rw
    networks:
      - ai-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on: [ollama, hermes-rag]
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - ai-net

  opencode-gui:
    build: ./opencode-gui
    container_name: opencode-gui
    ports:
      - "6080:6080"
    networks:
      - ai-net

  llamacpp:
    build: ./llamacpp-gui
    container_name: llamacpp
    volumes:
      - /media/sacha/de202ea4-0195-4fcc-85f1-3ca679ce2cdf1/models:/models:ro
    ports:
      - "8090:8090"
    networks:
      - ai-net

  chatbot-ui:
    image: ghcr.io/mckaywrigley/chatbot-ui:main
    container_name: chatbot-ui
    ports:
      - "3001:3000"
    environment:
      - OPENAI_API_HOST=http://llamacpp:8090
      - OPENAI_API_KEY=not-needed
    networks:
      - ai-net
    depends_on:
      - llamacpp

networks:
  ai-net:
    driver: bridge
