FROM fedora-minimal:43
RUN microdnf install -y git make gcc-c++ cmake python3-pip tar gzip && microdnf clean all
RUN git clone https://github.com/ggerganov/llama.cpp /app
WORKDIR /app
RUN cmake -B build && cmake --build build --config Release
EXPOSE 8090
# Lancement sur le port 8090
CMD ["./build/bin/llama-server", "--host", "0.0.0.0", "--port", "8090", "--model", "/models/granite-2b-test.gguf"]
